"""fix: delete on cascade books by novelist_id

Revision ID: 8d8edfbb8762
Revises: 60a7e2991137
Create Date: 2026-01-06 18:42:51.358699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8edfbb8762'
down_revision: Union[str, Sequence[str], None] = '60a7e2991137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_id_novelist_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'novelists', ['id_novelist'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_id_novelist_fkey'), 'books', 'novelists', ['id_novelist'], ['id'])
    # ### end Alembic commands ###
